import { Platform, StyleSheet } from 'react-native';

export const colors = {
  bg: '#0d0b09', panel: '#14100c', panel2: '#16120e', amber: '#f5a623',
  gold: '#d4af37', muted: '#8c7355', text: '#e6dacb', border: '#33271a', danger: '#d85b4b'
};

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.bg },
  header: { paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#2a2015', backgroundColor: colors.panel },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { color: colors.amber, fontSize: 16, fontWeight: 'bold', letterSpacing: 1.2 },
  headerSubtitle: { color: colors.muted, fontSize: 10, letterSpacing: 1, marginTop: 2 },
  playingAs: { color: colors.text, fontSize: 10, marginTop: 5 },
  playingAsName: { color: colors.amber, fontWeight: 'bold' },
  headerActions: { flexDirection: 'row', marginTop: 9 },
  headerBtn: { borderWidth: 1, borderColor: '#4a3a28', borderRadius: 5, paddingHorizontal: 9, paddingVertical: 6, marginRight: 6, backgroundColor: '#1a140f' },
  headerBtnPrimary: { backgroundColor: colors.amber, borderColor: colors.amber },
  headerBtnText: { color: '#b99a73', fontSize: 9, fontWeight: 'bold' },
  headerBtnTextPrimary: { color: colors.bg },

  targetBar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#110d0a', borderBottomWidth: 1, borderBottomColor: '#221a12' },
  targetLabel: { color: colors.muted, fontSize: 10, fontWeight: 'bold', marginRight: 8 },
  targetChip: { backgroundColor: '#1a140f', borderWidth: 1, borderColor: colors.border, borderRadius: 4, paddingHorizontal: 10, paddingVertical: 5, marginRight: 6 },
  targetChipActive: { backgroundColor: colors.amber, borderColor: colors.amber },
  chipText: { color: '#a68b68', fontSize: 11, fontWeight: 'bold' },
  chipTextActive: { color: colors.bg },

  listContent: { padding: 12, paddingBottom: 18 },
  systemBubble: { backgroundColor: '#1c1610', borderWidth: 1, borderColor: '#3a2e1e', borderRadius: 6, padding: 10, marginVertical: 6, alignItems: 'center' },
  systemText: { color: colors.gold, fontSize: 11, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  msgContainer: { flexDirection: 'row', marginVertical: 6, maxWidth: '88%' },
  playerAlign: { alignSelf: 'flex-end' },
  charAlign: { alignSelf: 'flex-start' },
  avatarBadge: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#261e16', borderWidth: 1, borderColor: '#4a3a28', justifyContent: 'center', alignItems: 'center', marginRight: 8 },
  avatarText: { fontSize: 16 },
  bubble: { borderRadius: 8, padding: 10, borderWidth: 1 },
  playerBubble: { backgroundColor: '#261c0e', borderColor: '#59401f' },
  charBubble: { backgroundColor: '#16120e', borderColor: '#33281c' },
  msgHeader: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', marginBottom: 4 },
  speakerName: { color: colors.amber, fontSize: 11, fontWeight: 'bold', marginRight: 6 },
  roleBadge: { color: '#ae8f69', fontSize: 9, marginRight: 5 },
  tagBadge: { color: '#e67e22', fontSize: 9, fontWeight: 'bold', marginRight: 4 },
  msgText: { color: colors.text, fontSize: 14, lineHeight: 19 },
  typingContainer: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 6 },
  typingText: { color: colors.amber, fontSize: 11, marginLeft: 8, fontWeight: 'bold' },

  inputContainer: { flexDirection: 'row', alignItems: 'center', padding: 10, backgroundColor: colors.panel, borderTopWidth: 1, borderTopColor: '#2a2015' },
  shoutBtn: { padding: 8, borderWidth: 1, borderColor: '#3a2e1e', borderRadius: 6, marginRight: 8, backgroundColor: '#1a140f' },
  shoutBtnActive: { backgroundColor: '#e67e22', borderColor: '#e67e22' },
  shoutText: { fontSize: 16 },
  input: { flex: 1, backgroundColor: colors.bg, borderWidth: 1, borderColor: colors.border, borderRadius: 6, color: colors.amber, paddingHorizontal: 12, paddingVertical: 8, fontSize: 14 },
  sendBtn: { backgroundColor: colors.amber, borderRadius: 6, paddingHorizontal: 16, paddingVertical: 10, marginLeft: 8 },
  sendBtnDisabled: { opacity: 0.5 },
  sendBtnText: { color: colors.bg, fontSize: 12, fontWeight: 'bold' },

  modalBg: { flex: 1, backgroundColor: 'rgba(0,0,0,0.88)', justifyContent: 'center', padding: 16 },
  modalCard: { backgroundColor: colors.panel2, borderWidth: 1, borderColor: '#4a3a28', borderRadius: 8, padding: 18, maxHeight: '90%' },
  modalTitle: { color: colors.amber, fontSize: 16, fontWeight: 'bold', marginBottom: 14, textAlign: 'center' },
  sectionTitle: { color: colors.gold, fontSize: 11, fontWeight: 'bold', letterSpacing: 1, marginTop: 14, marginBottom: 6 },
  inputLabel: { color: '#a68b68', fontSize: 10, fontWeight: 'bold', marginTop: 9, marginBottom: 4 },
  helperText: { color: '#6f5b43', fontSize: 10, lineHeight: 14, marginTop: 4 },
  modalInput: { backgroundColor: colors.bg, borderWidth: 1, borderColor: colors.border, borderRadius: 6, color: colors.amber, paddingHorizontal: 12, paddingVertical: 9, fontSize: 13 },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 18 },
  modalCancelBtn: { paddingHorizontal: 14, paddingVertical: 10, marginRight: 8 },
  modalCancelText: { color: colors.muted, fontSize: 12, fontWeight: 'bold' },
  modalSaveBtn: { backgroundColor: colors.amber, borderRadius: 6, paddingHorizontal: 15, paddingVertical: 10 },
  modalSaveText: { color: colors.bg, fontSize: 12, fontWeight: 'bold' },

  roleGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  roleChip: { width: '48%', marginRight: '2%', marginBottom: 7, borderWidth: 1, borderColor: colors.border, backgroundColor: '#110d0a', borderRadius: 6, padding: 9 },
  roleChipActive: { backgroundColor: '#35230d', borderColor: colors.amber },
  roleName: { color: colors.text, fontSize: 11, fontWeight: 'bold' },
  roleNameActive: { color: colors.amber },
  roleMeta: { color: colors.muted, fontSize: 9, marginTop: 2 },

  sessionNewBtn: { backgroundColor: colors.amber, padding: 11, borderRadius: 6, marginBottom: 10, alignItems: 'center' },
  sessionNewText: { color: colors.bg, fontWeight: 'bold', fontSize: 11 },
  sessionRow: { borderWidth: 1, borderColor: colors.border, backgroundColor: '#110d0a', borderRadius: 7, padding: 11, marginBottom: 8 },
  sessionRowActive: { borderColor: colors.amber, backgroundColor: '#21180e' },
  sessionTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sessionTitle: { color: colors.text, fontSize: 12, fontWeight: 'bold', flex: 1 },
  sessionActiveLabel: { color: colors.amber, fontSize: 8, fontWeight: 'bold', marginLeft: 7 },
  sessionMeta: { color: colors.muted, fontSize: 9, marginTop: 4 },
  sessionPreview: { color: '#ad9c88', fontSize: 10, marginTop: 5 },
  deleteText: { color: colors.danger, fontSize: 9, fontWeight: 'bold', marginTop: 7 },

  crewCard: { flexDirection: 'row', borderWidth: 1, borderColor: colors.border, backgroundColor: '#110d0a', borderRadius: 7, padding: 11, marginBottom: 8 },
  crewAvatar: { fontSize: 24, marginRight: 11 },
  crewInfo: { flex: 1 },
  crewName: { color: colors.text, fontSize: 12, fontWeight: 'bold' },
  crewRole: { color: colors.amber, fontSize: 9, fontWeight: 'bold', marginTop: 2 },
  crewDescription: { color: '#9d8970', fontSize: 10, lineHeight: 14, marginTop: 4 },
  controlledBadge: { color: colors.gold, fontSize: 9, fontWeight: 'bold', marginTop: 5 }
});
